#!/bin/sh
# SPDX-license-identifier: LGPL-2.1

set -e

function die() {
        echo "$(basename ${0}):" $@
        exit 1
}

etc="/etc/brmgr.conf"

[ -r "$etc" ] && . "$etc" || die \
        "could not read configuration file: $etc"

test -n "$bridge" -a -n "$addr" -a -n "$netmask" -a -n "$network" || die \
        "missing config variable(s)"

test ! -d /sys/class/net/${bridge} || die \
	"bridge already exists, not starting"

brctl addbr ${bridge} || die \
	"missing bridge support in kernel"

echo 1 > /proc/sys/net/ipv4/ip_forward

ip addr add ${addr}/${netmask} dev ${bridge}
ip link set ${bridge} up

ipt_lock="-w"
iptables -w -l -n > /dev/null 2>&1 || ipt_lock=""

iptables $ipt_lock -I INPUT -i ${bridge} -p udp --dport 67 -j ACCEPT
iptables $ipt_lock -I INPUT -i ${bridge} -p tcp --dport 67 -j ACCEPT
iptables $ipt_lock -I INPUT -i ${bridge} -p udp --dport 53 -j ACCEPT
iptables $ipt_lock -I INPUT -i ${bridge} -p tcp --dport 53 -j ACCEPT
iptables $ipt_lock -I FORWARD -i ${bridge} -j ACCEPT
iptables $ipt_lock -I FORWARD -o ${bridge} -j ACCEPT
iptables $ipt_lock -t nat -A POSTROUTING -s ${network} ! -d ${network} -j MASQUERADE
iptables $ipt_lock -t mangle -A POSTROUTING -o ${bridge} -p udp -m udp \
	--dport 68 -j CHECKSUM --checksum-fill
