#!/bin/sh
#  spdx-license-identifier: lgpl-2.1

set -e

function die() {
	echo "$(basename ${0}):" $@
	exit 1
}

etc="/etc/brmgr.conf"

[ -r "$etc" ] && . "$etc" || die \
	"could not read configuration file: $etc"

test -n "$bridge" -a -n "$addr" || die \
	"missing config variable(s)"

domain_arg=""
test -z "$domain" || domain_arg="-s $domain -s /$domain/"

exec dnsmasq $domain_arg -koz -u nobody \
	-i=${bridge} -I=lo -a=${addr} \
	-C=${dhcp_confile} -F=${dhcp_range} -X=${dhcp_max} -K --dhcp-no-override \
	-l=/var/lib/misc/dnsmasq.${bridge}.leases $@
