#!/bin/sh
# SPDX-license-identifier: LGPL-2.1

set -e

function die() {
        echo $(basename ${0}) $@
        exit 1
}

etc="/etc/brmgr.conf"

[ -r "$etc" ] && . "$etc" || die \
        "could not read configuration file: $etc"

test -n "$bridge" -a -n "$network" || die \
        "missing config variable(s)"

ls /sys/class/net/${bridge}/brif/* > /dev/null 2>&1 || die \
	"$bridge has attached interfaces, not shutting it down"

# Tear down bridge
if [ -d /sys/class/net/${bridge} ]; then
	use_iptables_lock="-w"
	iptables -w -L -n > /dev/null 2>&1 || use_iptables_lock=""
	ip link set ${bridge} down
	iptables $use_iptables_lock -D INPUT -i ${bridge} -p udp --dport 67 -j ACCEPT
	iptables $use_iptables_lock -D INPUT -i ${bridge} -p tcp --dport 67 -j ACCEPT
	iptables $use_iptables_lock -D INPUT -i ${bridge} -p udp --dport 53 -j ACCEPT
	iptables $use_iptables_lock -D INPUT -i ${bridge} -p tcp --dport 53 -j ACCEPT
	iptables $use_iptables_lock -D FORWARD -i ${bridge} -j ACCEPT
	iptables $use_iptables_lock -D FORWARD -o ${bridge} -j ACCEPT
	iptables $use_iptables_lock -t nat -D POSTROUTING -s ${network} ! -d ${network} \
		-j MASQUERADE || true
	iptables $use_iptables_lock -t mangle -D POSTROUTING -o ${bridge} -p udp -m udp \
		--dport 68 -j CHECKSUM --checksum-fill
	brctl delbr ${bridge}
fi
