#!/bin/sh
#  spdx-license-identifier: lgpl-2.1

set -e

function die() {
	echo "$(basename ${0}):" $@
	exit 2
}

etc="/etc/brmgr.conf"

[ -r "$etc" ] && . "$etc" || die \
	"could not read configuration file: $etc"

test -n "$bridge" -a -n "$addr" || die \
	"missing config variable(s)"

domain_arg=""
test -z "$domain" || domain_arg="-s $domain -s /$domain/"
ipv6_arg=""
test -z "$addr6" || ipv6_arg="--dhcp-range=${addr6},ra-only --listen-address ${addr6}"

exec dnsmasq $domain_arg -k -o -z -u nobody \
	-i ${bridge} -I lo -a ${addr} \
	--conf-file="${dhcp_conffile}" --dhcp-hostsfile="${dhcp_hostsfile}" \
	$ipv6_arg -F "${dhcp_range}" -X ${dhcp_max} -K --dhcp-no-override \
	-l /var/lib/misc/dnsmasq.${bridge}.leases $@
